title: Roy Xing
owner: Roy Xing
email: royx@bu.edu
description: My portfolio website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rx-00.github.io" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username:
github_username: RX-00
disqus_username: 

# Build settings
markdown: kramdown
# theme: minima

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->

collections:
  - projects
